# Generated by Django 5.1.4 on 2025-01-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("name", models.CharField(max_length=20)),
                (
                    "student_id",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("password", models.CharField(max_length=20)),
                ("major", models.CharField(max_length=40)),
                (
                    "sub_major_type",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                ("sub_major", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "micro_degree",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
            ],
        ),
    ]