# Generated by Django 5.1.4 on 2025-01-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_micro_degree"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="micro_degree",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=100),
        ),
    ]