# Generated by Django 5.1.4 on 2025-02-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_user_major_alter_user_micro_degree_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="done_general",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="done_major",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="done_rest",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="need_general",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="need_major",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="need_rest",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
    ]
