# Generated by Django 5.1.4 on 2025-02-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_user_done_general_user_done_major_user_done_rest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="done_sub_major",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="need_sub_major",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
    ]