# Generated by Django 5.1.4 on 2025-02-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_user_done_sub_major_user_need_sub_major"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="done_major_rest",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
    ]