# Generated by Django 5.1.4 on 2025-02-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_user_done_major_rest"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="done_sub_major_rest",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
    ]