# Generated by Django 5.1.4 on 2025-02-10 07:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_user_done_sub_major_rest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="done_sub_major_rest",
        ),
    ]