# Generated by Django 5.1.4 on 2025-02-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_remove_user_done_sub_major_rest"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="done_micro_degree",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
    ]
