# Generated by Django 5.1.4 on 2025-03-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_user_done_micro_degree"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorCount",
            fields=[
                (
                    "id",
                    models.IntegerField(default=1, primary_key=True, serialize=False),
                ),
                (
                    "total_visitor",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "today_visitor",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
            ],
        ),
    ]
