# Generated by Django 5.1.4 on 2025-03-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_visitorcount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitorcount",
            name="session_id",
            field=models.CharField(
                default="default",
                max_length=255,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="visitorcount",
            name="visit_time",
            field=models.DateField(null=True, unique=True),
        ),
    ]
