# Generated by Django 5.1.4 on 2025-03-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_visitorcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorCount',
        ),
    ]
