# Generated by Django 5.1.4 on 2025-03-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_delete_visitorcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorCount',
            fields=[
                ('session_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('visit_date', models.DateField(null=True, unique=True)),
            ],
        ),
    ]
