# Generated by Django 5.1.4 on 2025-03-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_date_time_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_time_joined',
            field=models.DateTimeField(),
        ),
    ]
