# Generated by Django 5.1.4 on 2025-03-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0012_alter_visitorcount_session_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitorcount",
            name="session_id",
            field=models.CharField(
                max_length=255, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
