# Generated by Django 5.1.4 on 2025-03-03 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0013_alter_visitorcount_session_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visitorcount",
            old_name="visit_time",
            new_name="visit_date",
        ),
    ]
