# Generated by Django 5.1.4 on 2025-03-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_visitorcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorcount',
            name='visit_date',
            field=models.DateField(default='2025-03-03'),
            preserve_default=False,
        ),
    ]
