# Generated by Django 5.1.4 on 2025-03-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_visitorcount_visit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorCookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visitor', models.IntegerField(default=0)),
                ('today_visitor', models.IntegerField(default=0)),
            ],
        ),
    ]
