# Generated by Django 5.1.4 on 2025-03-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0014_rename_visit_time_visitorcount_visit_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitorcount",
            name="visit_date",
            field=models.DateField(default="2025-03-02"),
            preserve_default=False,
        ),
    ]
