# Generated by Django 5.1.4 on 2025-04-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0016_rename_done_rest_user_done_general_rest"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="done_rest",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
    ]
