# Generated by Django 5.1.4 on 2025-04-10 15:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0018_rename_need_major_user_lack_major"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="need_sub_major",
            new_name="lack_sub_major",
        ),
    ]
