# Generated by Django 5.1.4 on 2025-04-10 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0019_rename_need_sub_major_user_lack_sub_major"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="done_micro_degree",
            new_name="done_MD",
        ),
    ]
