# Generated by Django 5.1.4 on 2025-04-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0021_user_done_sub_major_rest"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="micro_degree",
            new_name="MD",
        ),
        migrations.AddField(
            model_name="user",
            name="done_MD_rest",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
    ]
