# Generated by Django 5.1.4 on 2025-04-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_user_lack_md'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='done_general',
            new_name='done_GE',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='done_general_rest',
            new_name='done_GE_rest',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='need_general',
            new_name='lack_GE',
        ),
    ]
