# Generated by Django 5.1.4 on 2025-05-02 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_rename_done_general_user_done_ge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='need_rest',
            new_name='lack_rest',
        ),
    ]
