# Generated by Django 5.1.4 on 2025-06-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_rename_need_rest_user_lack_rest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='done_education',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lack_education',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
