# Generated by Django 5.1.4 on 2025-06-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_user_done_education_user_lack_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='done_education_rest',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
