# Generated by Django 5.1.4 on 2025-06-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_user_done_education_rest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='done_education',
        ),
    ]
