# Generated by Django 5.1.4 on 2025-10-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0028_remove_user_done_education"),
    ]

    operations = [
        migrations.CreateModel(
            name="MajorMap",
            fields=[
                ("college", models.CharField(blank=True, max_length=100, null=True)),
                ("major_label", models.CharField(max_length=100, unique=True)),
                (
                    "major_code",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("major_type", models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
