# Generated by Django 5.1.4 on 2025-10-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0029_major"),
    ]

    operations = [
        migrations.CreateModel(
            name="MajorAlias",
            fields=[
                ("major_code", models.CharField(max_length=100)),
                (
                    "alias",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
        ),
    ]
