# Generated by Django 5.1.4 on 2025-01-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyDoneLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5)),
                ('semester', models.CharField(max_length=5)),
                ('lecture_type', models.CharField(max_length=50)),
                ('lecture_topic', models.CharField(blank=True, max_length=200, null=True)),
                ('lecture_name', models.CharField(max_length=200)),
                ('credit', models.DecimalField(decimal_places=1, max_digits=3)),
                ('grade', models.CharField(max_length=5)),
            ],
        ),
    ]
