# Generated by Django 5.1.4 on 2025-01-22 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllLectureData',
            fields=[
                ('alllecture_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=5)),
                ('semester', models.CharField(max_length=5)),
                ('lecture_code', models.CharField(max_length=50)),
                ('lecture_name', models.CharField(max_length=100)),
                ('lecture_type', models.CharField(max_length=50)),
                ('lecture_topic', models.CharField(blank=True, max_length=200, null=True)),
                ('credit', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='MyDoneLecture',
            fields=[
                ('mydone_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=5)),
                ('semester', models.CharField(max_length=5)),
                ('lecture_type', models.CharField(max_length=50)),
                ('lecture_topic', models.CharField(blank=True, max_length=200, null=True)),
                ('lecture_name', models.CharField(max_length=200)),
                ('credit', models.DecimalField(decimal_places=1, max_digits=3)),
                ('grade', models.CharField(max_length=5)),
                ('alllecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduation.alllecturedata')),
            ],
        ),
    ]
