# Generated by Django 5.1.4 on 2025-02-08 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AllLectureData",
            fields=[
                ("alllecture_id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.CharField(max_length=5)),
                ("semester", models.CharField(max_length=5)),
                ("lecture_code", models.CharField(max_length=50)),
                ("lecture_name", models.CharField(max_length=100)),
                ("lecture_type", models.CharField(max_length=50)),
                (
                    "lecture_topic",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("credit", models.DecimalField(decimal_places=1, max_digits=3)),
                ("major_code", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="liberRequire",
            fields=[
                ("liber_id", models.AutoField(primary_key=True, serialize=False)),
                ("연도", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "인간학",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "봉사활동",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "VERUM캠프",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "논리적사고와글쓰기",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "창의적사고와코딩",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "외국어",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "고전탐구",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "사유와지혜",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "가치와실천",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "상상력과표현",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "인문융합",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "균형1",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "균형2",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "균형3",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "균형4",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "MSC교과군",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "계열기초",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "철학적인간학",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "신학적인간학",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NowLectureData",
            fields=[
                ("nowlecture_id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.CharField(max_length=5)),
                ("semester", models.CharField(max_length=5)),
                ("lecture_code", models.CharField(max_length=50)),
                ("lecture_name", models.CharField(max_length=100)),
                ("lecture_type", models.CharField(max_length=50)),
                (
                    "lecture_topic",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("credit", models.DecimalField(decimal_places=1, max_digits=3)),
                ("major_code", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Standard",
            fields=[
                ("index", models.AutoField(primary_key=True, serialize=False)),
                ("college", models.CharField(max_length=50)),
                ("year", models.CharField(max_length=30)),
                ("total_credit", models.DecimalField(decimal_places=1, max_digits=5)),
                (
                    "sub_major_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "sub_major_credit",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("major_credit", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "general_essential_credit",
                    models.DecimalField(decimal_places=1, max_digits=4),
                ),
                (
                    "general_selection_credit",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "rest_credit",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "micro_degree_credit",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MyDoneLecture",
            fields=[
                ("mydone_id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.CharField(max_length=5)),
                ("semester", models.CharField(max_length=5)),
                ("lecture_type", models.CharField(max_length=50)),
                (
                    "lecture_topic",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "lecture_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("lecture_name", models.CharField(max_length=200)),
                ("credit", models.DecimalField(decimal_places=1, max_digits=3)),
                ("grade", models.CharField(blank=True, max_length=5, null=True)),
                ("user_id", models.CharField(max_length=30, null=True)),
                (
                    "alllecture",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="graduation.alllecturedata",
                    ),
                ),
            ],
        ),
    ]
