# Generated by Django 5.1.4 on 2025-01-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0002_mydonelecture_lecture_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='alllecturedata',
            name='major_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
