# Generated by Django 5.1.4 on 2025-02-02 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0003_alllecturedata_major_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='NowLectureData',
            fields=[
                ('nowlecture_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=5)),
                ('semester', models.CharField(max_length=5)),
                ('lecture_code', models.CharField(max_length=50)),
                ('lecture_name', models.CharField(max_length=100)),
                ('lecture_type', models.CharField(max_length=50)),
                ('lecture_topic', models.CharField(blank=True, max_length=200, null=True)),
                ('credit', models.DecimalField(decimal_places=1, max_digits=3)),
                ('major_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mydonelecture',
            name='nowlecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graduation.nowlecturedata'),
        ),
    ]
