# Generated by Django 5.1.4 on 2025-02-02 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0006_alter_mydonelecture_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydonelecture',
            name='nowlecture',
        ),
    ]
