# Generated by Django 5.1.4 on 2025-02-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0007_remove_mydonelecture_nowlecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='liberRequire',
            fields=[
                ('liber_id', models.AutoField(primary_key=True, serialize=False)),
                ('liber_year', models.CharField(blank=True, max_length=30, null=True)),
                ('human_stu', models.CharField(blank=True, max_length=5, null=True)),
                ('verum', models.CharField(blank=True, max_length=5, null=True)),
                ('writing_stu', models.CharField(blank=True, max_length=5, null=True)),
                ('coding_stu', models.CharField(blank=True, max_length=5, null=True)),
                ('foreign_stu', models.CharField(blank=True, max_length=5, null=True)),
                ('oldbook_stu', models.CharField(blank=True, max_length=5, null=True)),
                ('wisdom_stu', models.CharField(blank=True, max_length=5, null=True)),
                ('value_stu', models.CharField(blank=True, max_length=5, null=True)),
                ('fantasy_stu', models.CharField(blank=True, max_length=5, null=True)),
                ('human_add', models.CharField(blank=True, max_length=5, null=True)),
                ('balance1', models.CharField(blank=True, max_length=5, null=True)),
                ('balance2', models.CharField(blank=True, max_length=5, null=True)),
                ('balance3', models.CharField(blank=True, max_length=5, null=True)),
                ('balance4', models.CharField(blank=True, max_length=5, null=True)),
                ('msc_stu', models.CharField(blank=True, max_length=5, null=True)),
                ('basic_stu', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
