# Generated by Django 5.1.4 on 2025-02-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graduation", "0007_remove_mydonelecture_nowlecture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Standard",
            fields=[
                ("index", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name="mydonelecture",
            name="user_id",
            field=models.CharField(default="", max_length=30),
        ),
    ]
