# Generated by Django 5.1.4 on 2025-02-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0006_alter_mydonelecture_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='liberrequire',
            name='service_stu',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
