# Generated by Django 5.1.4 on 2025-02-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graduation", "0009_alter_mydonelecture_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="standard",
            name="college",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="standard",
            name="general_essential_credit",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="standard",
            name="general_selection_credit",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="standard",
            name="major_credit",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="standard",
            name="micro_degree_credit",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="standard",
            name="rest_credit",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="standard",
            name="sub_major_credit",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="standard",
            name="sub_major_type",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="standard",
            name="year",
            field=models.CharField(default="", max_length=30),
        ),
    ]
