# Generated by Django 5.1.4 on 2025-02-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0010_alter_liberrequire_balance1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liberrequire',
            name='god_human_stu',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='liberrequire',
            name='past_human_stu',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
