# Generated by Django 5.1.4 on 2025-02-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graduation", "0011_alter_standard_college_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="standard",
            name="total_credit",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
