# Generated by Django 5.1.4 on 2025-02-05 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0011_liberrequire_god_human_stu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liberrequire',
            old_name='balance1',
            new_name='MSC교과군',
        ),
        migrations.RenameField(
            model_name='liberrequire',
            old_name='balance2',
            new_name='VERUM캠프',
        ),
        migrations.RenameField(
            model_name='liberrequire',
            old_name='balance3',
            new_name='가치와실천',
        ),
        migrations.RenameField(
            model_name='liberrequire',
            old_name='balance4',
            new_name='계열기초',
        ),
        migrations.RenameField(
            model_name='liberrequire',
            old_name='basic_stu',
            new_name='고전탐구',
        ),
        migrations.RenameField(
            model_name='liberrequire',
            old_name='coding_stu',
            new_name='균형1',
        ),
        migrations.RenameField(
            model_name='liberrequire',
            old_name='fantasy_stu',
            new_name='균형2',
        ),
        migrations.RenameField(
            model_name='liberrequire',
            old_name='foreign_stu',
            new_name='균형3',
        ),
        migrations.RenameField(
            model_name='liberrequire',
            old_name='god_human_stu',
            new_name='균형4',
        ),
        migrations.RenameField(
            model_name='liberrequire',
            old_name='human_add',
            new_name='논리적사고와글쓰기',
        ),
        migrations.RenameField(
            model_name='liberrequire',
            old_name='human_stu',
            new_name='봉사와실천',
        ),
        migrations.RenameField(
            model_name='liberrequire',
            old_name='msc_stu',
            new_name='사유와지혜',
        ),
        migrations.RenameField(
            model_name='liberrequire',
            old_name='oldbook_stu',
            new_name='상상력과표현',
        ),
        migrations.RenameField(
            model_name='liberrequire',
            old_name='past_human_stu',
            new_name='신학적인간학',
        ),
        migrations.RenameField(
            model_name='liberrequire',
            old_name='liber_year',
            new_name='연도',
        ),
        migrations.RenameField(
            model_name='liberrequire',
            old_name='service_stu',
            new_name='외국어',
        ),
        migrations.RenameField(
            model_name='liberrequire',
            old_name='value_stu',
            new_name='인간학',
        ),
        migrations.RenameField(
            model_name='liberrequire',
            old_name='verum',
            new_name='인문융합',
        ),
        migrations.RenameField(
            model_name='liberrequire',
            old_name='wisdom_stu',
            new_name='창의적사고와코딩',
        ),
        migrations.RenameField(
            model_name='liberrequire',
            old_name='writing_stu',
            new_name='철학적인간학',
        ),
    ]
