# Generated by Django 5.1.4 on 2025-02-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0012_rename_balance1_liberrequire_msc교과군_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydonelecture',
            name='user_id',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
