# Generated by Django 5.1.4 on 2025-02-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graduation", "0012_standard_total_credit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standard",
            name="total_credit",
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
