# Generated by Django 5.1.4 on 2025-02-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0013_mydonelecture_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydonelecture',
            name='user_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
