# Generated by Django 5.1.4 on 2025-02-07 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0014_alter_standard_rest_credit'),
        ('graduation', '0015_rename_봉사와실천_liberrequire_봉사활동'),
    ]

    operations = [
    ]
