# Generated by Django 5.1.4 on 2025-02-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0017_liberrequire_alllecture_alter_mydonelecture_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydonelecture',
            name='grade',
        ),
    ]
