# Generated by Django 5.1.4 on 2025-02-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graduation", "0018_remove_liberrequire_alllecture"),
    ]

    operations = [
        migrations.AddField(
            model_name="mydonelecture",
            name="user_id",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
