# Generated by Django 5.1.4 on 2025-02-10 05:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("graduation", "0022_alter_standard_college_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mydonelecture",
            name="grade",
        ),
    ]
