# Generated by Django 5.1.4 on 2025-02-09 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0018_remove_mydonelecture_grade'),
        ('graduation', '0022_alter_standard_college_and_more'),
    ]

    operations = [
    ]
