# Generated by Django 5.1.4 on 2025-03-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0023_remove_mydonelecture_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydonelecture',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
    ]
