# Generated by Django 5.1.4 on 2025-02-09 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0018_remove_liberrequire_alllecture'),
        ('graduation', '0023_merge_20250210_0628'),
    ]

    operations = [
    ]
