# Generated by Django 5.1.4 on 2025-04-10 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("graduation", "0024_mydonelecture_can_delete"),
    ]

    operations = [
        migrations.RenameField(
            model_name="standard",
            old_name="total_credit",
            new_name="total_standard",
        ),
    ]
