# Generated by Django 5.1.4 on 2025-04-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0025_liberrequire_문제해결_liberrequire_소통_liberrequire_융합비고_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liberrequire',
            name='트리니티아카데미',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
