# Generated by Django 5.1.4 on 2025-04-10 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("graduation", "0025_rename_total_credit_standard_total_standard"),
    ]

    operations = [
        migrations.RenameField(
            model_name="standard",
            old_name="major_credit",
            new_name="major_standard",
        ),
    ]
