# Generated by Django 5.1.4 on 2025-04-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0026_liberrequire_트리니티아카데미'),
    ]

    operations = [
        migrations.AddField(
            model_name='liberrequire',
            name='디지털소통',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
