# Generated by Django 5.1.4 on 2025-04-10 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "graduation",
            "0028_rename_general_selection_credit_standard_choice_ge_standard",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="standard",
            old_name="rest_credit",
            new_name="rest_standard",
        ),
    ]
