# Generated by Django 5.1.4 on 2025-04-17 22:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("graduation", "0030_rename_sub_major_credit_standard_sub_major_standard"),
    ]

    operations = [
        migrations.RenameField(
            model_name="standard",
            old_name="micro_degree_credit",
            new_name="MD_standard",
        ),
    ]
