# Generated by Django 5.1.4 on 2025-04-20 04:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("graduation", "0031_rename_micro_degree_credit_standard_md_standard"),
    ]

    operations = [
        migrations.RenameField(
            model_name="standard",
            old_name="essential_GE_standatd",
            new_name="essential_GE_standard",
        ),
    ]
