# Generated by Django 5.1.4 on 2025-04-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0033_liberrequire_디지털소통_liberrequire_문제해결_liberrequire_소통_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='liberRequire',
            new_name='GEStandard',
        ),
    ]
