# Generated by Django 5.1.4 on 2025-05-02 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0034_rename_liberrequire_gestandard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gestandard',
            old_name='liber_id',
            new_name='GEStandard_id',
        ),
    ]
