# Generated by Django 5.1.4 on 2025-06-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0035_rename_liber_id_gestandard_gestandard_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='education_standard',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
