# Generated by Django 5.1.4 on 2025-06-12 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("graduation", "0036_standard_education_standard"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standard",
            name="education_standard",
        ),
    ]
