# Generated by Django 5.1.4 on 2025-10-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0037_remove_standard_education_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydonelecture',
            name='matched_topic',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
