# Generated by Django 5.1.4 on 2025-02-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0005_alter_mydonelecture_alllecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydonelecture',
            name='grade',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
